### ISSUE TITLE
Double cousins scenario repeats people

### ISSUE THREAD

**Issue by SThakkar14** [PeWu/topola-viewer#75] opened 2021-12-27 09:08 UTC
I was using GRAMPS to see a family tree when I noticed that double cousins duplicates the people in the tree twice when you want to see the whole graph at once.

Double cousin explanation and a possible view:
https://en.wikipedia.org/wiki/Cousin#Multiplicities

**Comment by PeWu** [comment] 2021-12-30 11:55
This is a known problem.

Duplicate of #30

**Closed** 2021-12-30 11:56 UTC
