### ISSUE TITLE
Branching and recombining isn't shown correctly

### ISSUE THREAD

**Issue by endolith** [PeWu/topola-viewer#42] opened 2021-02-28 20:01 UTC
If a family tree contains married first cousins, the viewer doesn't want to display this, showing the grandparents twice, as if they are separate couples with the same name.  Can it combine them together instead of duplicating them?

Instead of 

```
AB  AB
|    |
CD   EF
 |  |
  GH
```

It should be more like
  
```
  AB
 |  |
CD   EF
 |  |
  GH
```

**Comment by PeWu** [comment] 2021-04-09 22:05
Thanks @endolith.
This is a known issue and I don't know yet how to solve it well.

Duplicate of #30

**Comment by PeWu** [comment] 2021-04-09 22:05
Thanks @endolith.
This is a known issue and I don't know yet how to solve it well.

Duplicate of #30

**Closed by PeWu** 2021-04-09 22:05 UTC
